# Generated by Django 2.2.5 on 2019-11-26 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191126_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='main_cat_title',
            new_name='main_category',
        ),
        migrations.AlterField(
            model_name='mainarticle',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 4, 56, 24, 41964), verbose_name='date published'),
        ),
    ]
