# Generated by Django 2.2.5 on 2019-11-30 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191126_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(default='img/img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainarticle',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 2, 40, 38, 160205), verbose_name='date published'),
        ),
    ]
